/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	workloadv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/workload/v1alpha1"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// BootstrapAccelerateStrategyApplyConfiguration represents a declarative configuration of the BootstrapAccelerateStrategy type for use
// with apply.
//
// BootstrapAccelerateStrategy configures source-aware creation of role replicas.
type BootstrapAccelerateStrategyApplyConfiguration struct {
	// Provider is the weight transfer system used by the inference engines.
	Provider *workloadv1alpha1.BootstrapAccelerateStrategyProvider `json:"provider,omitempty"`
	// Roles limits acceleration to the named roles. Empty means all roles.
	Roles []string `json:"roles,omitempty"`
	// SeedReplicas limits role replicas created per pool while no ready source
	// exists. It is a positive integer or a percentage from 1% to 100% of
	// spec.replicas * role.replicas, rounded up (10% of 3 is 1).
	// The effective budget is at least the role's gang minimum in one ServingGroup.
	// A desired count of zero creates nothing.
	SeedReplicas *intstr.IntOrString `json:"seedReplicas,omitempty"`
	// SourceFanOut limits starting role replicas per ready replica in the same
	// pool. The effective budget is at least the role's gang minimum.
	SourceFanOut *int32 `json:"sourceFanOut,omitempty"`
	// ModelExpress configures environment injection for inference engines.
	// If unset, users configure the engine environment themselves.
	ModelExpress *ModelExpressConfigApplyConfiguration `json:"modelExpress,omitempty"`
}

// BootstrapAccelerateStrategyApplyConfiguration constructs a declarative configuration of the BootstrapAccelerateStrategy type for use with
// apply.
func BootstrapAccelerateStrategy() *BootstrapAccelerateStrategyApplyConfiguration {
	return &BootstrapAccelerateStrategyApplyConfiguration{}
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *BootstrapAccelerateStrategyApplyConfiguration) WithProvider(value workloadv1alpha1.BootstrapAccelerateStrategyProvider) *BootstrapAccelerateStrategyApplyConfiguration {
	b.Provider = &value
	return b
}

// WithRoles adds the given value to the Roles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Roles field.
func (b *BootstrapAccelerateStrategyApplyConfiguration) WithRoles(values ...string) *BootstrapAccelerateStrategyApplyConfiguration {
	for i := range values {
		b.Roles = append(b.Roles, values[i])
	}
	return b
}

// WithSeedReplicas sets the SeedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SeedReplicas field is set to the value of the last call.
func (b *BootstrapAccelerateStrategyApplyConfiguration) WithSeedReplicas(value intstr.IntOrString) *BootstrapAccelerateStrategyApplyConfiguration {
	b.SeedReplicas = &value
	return b
}

// WithSourceFanOut sets the SourceFanOut field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceFanOut field is set to the value of the last call.
func (b *BootstrapAccelerateStrategyApplyConfiguration) WithSourceFanOut(value int32) *BootstrapAccelerateStrategyApplyConfiguration {
	b.SourceFanOut = &value
	return b
}

// WithModelExpress sets the ModelExpress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModelExpress field is set to the value of the last call.
func (b *BootstrapAccelerateStrategyApplyConfiguration) WithModelExpress(value *ModelExpressConfigApplyConfiguration) *BootstrapAccelerateStrategyApplyConfiguration {
	b.ModelExpress = value
	return b
}
