/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ModelExpressConfigApplyConfiguration represents a declarative configuration of the ModelExpressConfig type for use
// with apply.
//
// ModelExpressConfig configures the ModelExpress inference-engine containers.
type ModelExpressConfigApplyConfiguration struct {
	// EngineContainers names regular inference-engine containers in entry and
	// worker Pods of in-scope roles. Sidecars and init containers are not selected.
	EngineContainers []string `json:"engineContainers,omitempty"`
	// ServerAddress is the ModelExpress server's gRPC address (host:port).
	// It is injected as MX_SERVER_ADDRESS only if that variable is not already
	// set in the selected container. If empty, users supply the endpoint themselves.
	ServerAddress *string `json:"serverAddress,omitempty"`
	// ReadyURL is the engine endpoint that ModelExpress polls before a source
	// publishes its metadata; it may differ from the Pod readiness probe.
	// It is injected as MX_ARTIFACT_READY_URL only if that variable is not already
	// set in the selected container. If empty, ModelExpress uses the engine default.
	ReadyURL *string `json:"readyURL,omitempty"`
}

// ModelExpressConfigApplyConfiguration constructs a declarative configuration of the ModelExpressConfig type for use with
// apply.
func ModelExpressConfig() *ModelExpressConfigApplyConfiguration {
	return &ModelExpressConfigApplyConfiguration{}
}

// WithEngineContainers adds the given value to the EngineContainers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EngineContainers field.
func (b *ModelExpressConfigApplyConfiguration) WithEngineContainers(values ...string) *ModelExpressConfigApplyConfiguration {
	for i := range values {
		b.EngineContainers = append(b.EngineContainers, values[i])
	}
	return b
}

// WithServerAddress sets the ServerAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerAddress field is set to the value of the last call.
func (b *ModelExpressConfigApplyConfiguration) WithServerAddress(value string) *ModelExpressConfigApplyConfiguration {
	b.ServerAddress = &value
	return b
}

// WithReadyURL sets the ReadyURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyURL field is set to the value of the last call.
func (b *ModelExpressConfigApplyConfiguration) WithReadyURL(value string) *ModelExpressConfigApplyConfiguration {
	b.ReadyURL = &value
	return b
}
